// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4JKEx1jtrjr4rG-2E225OCSCG-7aecM',
    appId: '1:704575791950:web:e78f77e460994c67acb41f',
    messagingSenderId: '704575791950',
    projectId: 'docusys-mobile',
    authDomain: 'docusys-mobile.firebaseapp.com',
    storageBucket: 'docusys-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJtOfiq-6UhRx3QYEAMnaz23SZW80fD1E',
    appId: '1:704575791950:android:95850460d4d48d7aacb41f',
    messagingSenderId: '704575791950',
    projectId: 'docusys-mobile',
    storageBucket: 'docusys-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmXTbEKi_V8XQI_l9am5mi2GMM3AViyBM',
    appId: '1:704575791950:ios:2accdbe5967ae87dacb41f',
    messagingSenderId: '704575791950',
    projectId: 'docusys-mobile',
    storageBucket: 'docusys-mobile.firebasestorage.app',
    iosBundleId: 'com.example.docusysMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmXTbEKi_V8XQI_l9am5mi2GMM3AViyBM',
    appId: '1:704575791950:ios:2accdbe5967ae87dacb41f',
    messagingSenderId: '704575791950',
    projectId: 'docusys-mobile',
    storageBucket: 'docusys-mobile.firebasestorage.app',
    iosBundleId: 'com.example.docusysMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ4JKEx1jtrjr4rG-2E225OCSCG-7aecM',
    appId: '1:704575791950:web:913ce15462991e71acb41f',
    messagingSenderId: '704575791950',
    projectId: 'docusys-mobile',
    authDomain: 'docusys-mobile.firebaseapp.com',
    storageBucket: 'docusys-mobile.firebasestorage.app',
  );
}
